/// A simple data model representing a chat message.
///
/// * `text` – The message content.
/// * `isUser` – `true` if the message was sent by the user.
/// * `timestamp` – When the message was created.
/// * `imageUrl` – Optional URL for an image generated by DALL·E.
class Message {
  final String text;
  final bool isUser;
  final DateTime timestamp;
  final String? imageUrl;

  const Message({
    required this.text,
    required this.isUser,
    required this.timestamp,
    this.imageUrl,
  });

  @override
  String toString() =>
      'Message(text: $text, isUser: $isUser, timestamp: $timestamp, imageUrl: $imageUrl)';
}
